# Generated by Django 5.2.15 on 2026-07-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.ImageField(upload_to='locations/'),
        ),
    ]
